name: Test code
on: 
  push:
    paths:
     - server/**
jobs:
  Explore-GitHub-Actions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - run: cd server
    - run: npm install
    - run: npm test