name: Node.js CI
on:
  push:
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to server directory
      run: cd server

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test